python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py
python test.py | python2.7 2qsort.py | python check.py

